events/urls.py
from django.urls import path
from .views import event_create_and_list_view, like_unlike_event

app_name = 'events'

urlpatterns = [
    path('', event_create_and_list_view, name='main-event-view'),
    path('liked/', like_unlike_event, name='like-event-view'),
]

ignis/urls.py
from django.contrib import admin
from django.urls import path, include
# from rest_framework.documentation import include_docs_urls
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('events.urls')),
    # path('docs/', include_docs_urls(title="API Documentation"))
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

events/models.py
from django.db import models
from django.core.validators import FileExtensionValidator
from profiles.models import Profile


class Event(models.Model):
    name = models.CharField(max_length=100, blank=False)
    date = models.DateField()
    time = models.TimeField()
    location = models.TextField()
    image = models.ImageField(
        upload_to='images',
        validators=[FileExtensionValidator(['png', 'jpg', 'jpeg'])],
        blank=True
    )
    is_liked = models.ManyToManyField(Profile, blank=False, related_name='likes')

    def __str__(self):
        return str(self.name)

    def num_likes(self):
        return self.is_liked.all().count()


LIKE_CHOICES = (
    ('Like', 'Like'),
    ('Unlike', 'Unlike'),
)


class Like(models.Model):
    user = models.ForeignKey(Profile, on_delete=models.CASCADE)
    event = models.ForeignKey(Event, on_delete=models.CASCADE)
    value = models.CharField(choices=LIKE_CHOICES, max_length=8)
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.user}-{self.event}-{self.value}"

profiles/models.py
from django.db import models
from django.shortcuts import reverse
from django.contrib.auth.models import User
from django.template.defaultfilters import slugify


class Profile(models.Model):
    first_name = models.CharField(max_length=200, blank=True)
    last_name = models.CharField(max_length=200, blank=True)
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    email = models.EmailField(max_length=200, blank=True)
    slug = models.SlugField(unique=True, blank=True)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.user.username}-{self.created.strftime('%d-%m-%Y')}"

    def get_absolute_url(self):
        return reverse("profiles:profile-detail-view", kwargs={"slug": self.slug})

    __initial_first_name = None
    __initial_last_name = None

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.__initial_first_name = self.first_name
        self.__initial_last_name = self.last_name

    def save(self, *args, **kwargs):
        ex = False
        to_slug = self.slug
        if self.first_name != self.__initial_first_name or self.last_name != self.__initial_last_name or self.slug == "":
            if self.first_name and self.last_name:
                to_slug = slugify(str(self.first_name) + " " + str(self.last_name))
                ex = Profile.objects.filter(slug=to_slug).exists()
                while ex:
                    to_slug = slugify(to_slug + " " + str(get_random_code()))
                    ex = Profile.objects.filter(slug=to_slug).exists()
            else:
                to_slug = str(self.user)
        self.slug = to_slug
        super().save(*args, **kwargs)

events/forms.py
from django import forms
from .models import Event


class EventModelForm(forms.ModelForm):
    class Meta:
        model = Event
        fields = ('name', 'date', 'time', 'location', 'image')

events/views.py
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from .models import Event, Like
from profiles.models import Profile
from .forms import EventModelForm
from django.views.generic import UpdateView, DeleteView
from django.contrib import messages
from django.http import JsonResponse
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin


@login_required
def event_create_and_list_view(request):
    qs = Event.objects.all()
    profile = Profile.objects.get(user=request.user)

    # initials
    e_form = EventModelForm()
    event_added = False

    profile = Profile.objects.get(user=request.user)

    if 'submit_e_form' in request.POST:
        print(request.POST)
        e_form = EventModelForm(request.POST, request.FILES)
        if e_form.is_valid():
            instance = e_form.save(commit=False)
            instance.author = profile
            instance.save()
            p_form = EventModelForm()
            post_added = True

    context = {
        'qs': qs,
        'profile': profile,
        'e_form': e_form,
        'post_added': event_added,
    }

    return render(request, 'events/main.html', context)


@login_required
def like_unlike_event(request):
    user = request.user
    if request.method == 'POST':
        event_id = request.POST.get('event_id')
        event_obj = Event.objects.get(id=event_id)
        profile = Profile.objects.get(user=user)

        if profile in event_obj.is_liked.all():
            event_obj.is_liked.remove(profile)
        else:
            event_obj.is_liked.add(profile)

        like, created = Like.objects.get_or_create(user=profile, event_id=event_id)

        if not created:
            if like.value == 'Like':
                like.value = 'Unlike'
            else:
                like.value = 'Like'
        else:
            like.value = 'Like'

            event_obj.save()
            like.save()

        # data = {
        #     'value': like.value,
        #     'likes': event_obj.liked.all().count()
        # }

        # return JsonResponse(data, safe=False)
    return redirect('events:main-event-view')

events/templates/events/main.html
{% extends 'base.html' %}
{% block title %}main page{% endblock title %}
{% block content %}
    <div class="ui grid">
        <div class="eleven wide column" style="margin-right: auto; margin-left: auto">
            {% for obj in qs %}
                <div class="ui fluid card">
                    <div class="ui fluid image">
                        {% if obj.image %}
                            <img src="{{obj.image.url}}" >
                        {% endif %}
                        <div class="content">
                            <p> {{ obj.name }} </p>
                            <div class="right floated">
                                <form action="{% url 'events:like-event-view' %}" method="POST" class='like-form' id='{{obj.id}}'>
                                    {% csrf_token %}
                                    <input type="hidden" name="event_id" value={{obj.id}}>

                                    <button type="submit" class="ui button like-btn{{obj.id}}">
                                        {% if profile not in obj.is_liked.all %}
                                            ♡
                                        {% else %}
                                            ❤️
                                        {% endif %}
                                    </button>
{#                                    <div class="ui grid">#}
{#                                        <div class="column">#}
{#                                            <div class="like-count{{obj.id}}"> {{obj.num_likes}} </div>#}
{#                                        </div>#}
{#                                        <div class="column">#}
{#                                            likes#}
{#                                        </div>#}
{#                                    </div>#}
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock content %}

{% block scripts %}
    <script>
        $( document ).ready(function() {
            let display = false
            $(".cmt_btn").click(function () {
                if (display===false)
                {
                    $(this).next(".comment-box").show("slow");
                    display=true
                }
                else
                {
                    $(this).next(".comment-box").hide("slow");
                    display=false
                }
            });

            $('.like-form').submit(function(e){
                e.preventDefault()

                const event_id = $(this).attr('id')

                const likeText = $(`.like-btn${event_id}`).text()
                const trim = $.trim(likeText)

                const url = $(this).attr('action')

                let res;
                const likes = $(`.like-count${event_id}`).text()
                const trimCount = parseInt(likes)

                $.ajax({
                    type: 'POST',
                    url: url,
                    data: {
                        'csrfmiddlewaretoken': $('input[name=csrfmiddlewaretoken]').val(),
                        'event_id':event_id,
                    },
                    success: function(response) {
                        if(trim === '♡') {
                            $(`.like-btn${event_id}`).text('❤')
                            res = trimCount - 1
                        } else {
                            $(`.like-btn${event_id}`).text('♡')
                            res = trimCount + 1
                        }

                        $(`.like-count${event_id}`).text(res)
                    },
                    error: function(response) {
                        console.log('error', response)
                    }
                })
            })
        });
    </script>
{% endblock scripts %}

templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- jQuery -->
    <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
    <!--Custom css-->
    <link rel="stylesheet" type="text/css" href={% static 'style.css' %}>
    <!-- semantic UI -->
    <link rel="stylesheet" type='text/css' href="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.2.14/semantic.min.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.4.1/semantic.min.js"></script>


    <title>Ignis - {% block title %}{% endblock title %}</title>
  </head>
  <body>
    {% include 'main/navbar.html' %}
    <div class="ui container">
      {% block content %}
      {% endblock content %}
    </div>

    {% block scripts %}
    {% endblock scripts %}

   <!--Custom js ADD-->
   <script type="text/javascript" src={% static 'main.js' %}></script>

  </body>
</html>

templates/main/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

templates/main/navbar.html
{% url 'home-view' as path_to_home %}
{% url 'posts:main-post-view' as path_to_posts %}
{% url 'profiles:my-profile-view' as path_to_my_profile %}
{% url 'profiles:my-invites-view' as path_to_my_invites %}
{% url 'profiles:invite-profiles-view' as path_to_invites %}
{% url 'profiles:all-profiles-view' as path_to_all_profiles %}

<div class="ui inverted menu nav mb-7">
  <div class="ui container">
    <a href="{{path_to_home}}" class="{% if request.path == path_to_home %}active{% endif %} item">
        <h3>Ignis</h3>
    </a>

    <div class="right menu">
        {% if request.user.is_authenticated %}
             <div class="item">
              <form action="" method="GET">
                <div class="ui action left icon input">
                <input class="prompt" type="text" name='q' placeholder="Search for an event">
                <i class="search icon"></i>
                <button type='submit' class="ui button">Search</button>
                </div>
            </form>
            </div>

            <a href="{{path_to_my_profile}}" class="{% if request.path == path_to_my_profile %}active{% endif %} item">
                <img src={{picture.url}} class="ui avatar image">&nbsp;
                 {{ request.user }}
            </a>

            <a href="" class="ui item">
                Logout
            </a>
        {% else %}
        <a href="" class="ui item">
                Login
            </a>
        {% endif %}
    </div>
  </div>
</div>